---
title: "Reproducible Research Project 1"
author: "Akhil-Ahuja"
date: "27/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Necessary Packages

```{r loading necessary packages, echo=TRUE, error = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(lattice)
```

## Loading and Preprocessing the data

```{r downloading and reading and preprocessing data}
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", "repdata_data_activity.zip")
activity <- read.csv(unz("repdata_data_activity.zip", "activity.csv"), header = TRUE, na.strings = "NA")

head(activity)
summary(activity)
activity_cleaned <- activity[complete.cases(activity),]
activity_cleaned$date <- as.Date(activity_cleaned$date,"%Y-%m-%d")
head(activity_cleaned)
summary(activity_cleaned)
```

## What is mean total number of steps taken per day?

Mean is in red color and Median is in Blue color

```{r}
activity_per_day<- activity_cleaned %>% 
    group_by(date) %>% 
    summarise(total_steps = sum(steps), .groups = "keep")

median <- median(activity_per_day$total_steps, na.rm = TRUE)
median

mean <- round(mean(activity_per_day$total_steps, na.rm = TRUE), 2)
mean

hist(activity_per_day$total_steps, main = "Histogram of Number of Steps per day", xlab = "Number of Steps")

abline(v = median, col = "blue")
text (10000, 20, median, col = "blue", pos = 1, srt = 90)

abline(v = mean, col = "red", lty = 2)
text (11000, 20, mean, col = "red", pos = 1, srt = 90)
```


## What is the average daily activity pattern?

```{r}
activity_per_interval <- activity_cleaned %>% 
    group_by(interval) %>% 
    summarise(total_steps = sum(steps, na.rm = TRUE), .groups = "keep")

max <- max(activity_per_interval$total_steps, na.rm = TRUE)
max

plot(activity_per_interval$interval, activity_per_interval$total_steps, type = "l", main = "Time Series of Number of Steps per interval", xlab = "Interval", ylab = "Number of Steps")

text(1000, max, as.character(max), col = "red")
```

## Imputing missing values

Do Results vary, if code missing values as 5

```{r}
## cleaning
activity_NA_0 <- activity
activity_NA_0[is.na(activity_NA_0)] <- 5
head(activity_NA_0)
summary(activity_NA_0)

## missing values
nrow(activity_NA_0)-nrow(activity)

## histogram
activity_per_day<- activity_NA_0 %>% 
    group_by(date) %>% 
    summarise(total_steps = sum(steps), .groups = "keep")

median <- median(activity_per_day$total_steps, na.rm = TRUE)
median

mean <- round(mean(activity_per_day$total_steps, na.rm = TRUE), 2)
mean

hist(activity_per_day$total_steps, main = "Histogram of Number of Steps per day", xlab = "Number of Steps")

abline(v = median, col = "blue")
text (11000, 20, median, col = "blue", pos = 1, srt = 90)

abline(v = mean, col = "red", lty = 2)
text (8500, 20, mean, col = "red", pos = 1, srt = 90)

## time series
activity_per_interval <- activity_NA_0 %>% 
    group_by(interval) %>% 
    summarise(total_steps = sum(steps), .groups = "keep")

max <- max(activity_per_interval$total_steps)
max

plot(activity_per_interval$interval, activity_per_interval$total_steps, type = "l", main = "Time Series of Number of Steps per interval", xlab = "Interval", ylab = "Number of Steps")

text(1000, max, as.character(max), col = "red")
```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
activity_NA_0$date <- as.Date(activity_NA_0$date, "%Y-%m-%d")
activity_NA_0$day <- weekdays(activity_NA_0$date)
activity_NA_0$day_type <- "Weekday"
activity_NA_0$day_type[activity_NA_0$day %in% c("Saturday", "Sunday")] <- "Weekend"
activity_NA_0$day_type <- as.factor(activity_NA_0$day_type)

activity_per_interval <- activity_NA_0 %>% 
    group_by(interval, day_type) %>% 
    summarise(total_steps = sum(steps), .groups = "keep")

xyplot(total_steps~ interval| day_type, data = activity_per_interval, type = "l", layout = c(1,2), xlab = "Interval", ylab = "Number of steps")
```
